TOOL_REFORGES = {
    'gentle',
    'odd',
    'fast',
    'fair',
    'epic',
    'sharp',
    'heroic',
    'spicy',
    'legendary',
    'deadly',
    'fine',
    'grand',
    'hasty',
    'neat',
    'rapid',
    'unreal',
    'awkward',
    'rich',
    'clean',
    'fierce',
    'heavy',
    'light',
    'mythic',
    'pure',
    'smart',
    'titanic',
    'wise',
    'very',
    'highly',
    'extremely',
    'not so',
    'thicc',
    'absolutely',
    'even more',
    'bizarre',
    'itchy',
    'ominous',
    'pleasant',
    'pretty',
    'shiny',
    'simple',
    'strange',
    'vivid',
    'godly',
    'demonic',
    'forceful',
    'hurtful',
    'keen',
    'strong',
    'superior',
    'unpleasant',
    'zealous',
    'shaded',
    'silky',
    'salty',
    'treacherous',
    'stiff',
    'bloody',
    'sweet'
}

#fix spirit stnoe
TOOL_ITEM_REFORGES = {
    'HARDENED_WOOD': 'Stiff', 
    'ROCK_GEMSTONE': 'Auspicious', 
    'RARE_DIAMOND': 'Reinforced', 
    'JERRY_STONE': "Jerry's", 
    'RED_NOSE': 'Ridiculous', 
    'SHINY_PRISM': 'Glistening', 
    'SPIRIT_STONE': 'Spiritual', 
    'CANDY_CORN': 'Candied', 
    'SEARING_STONE': 'Strengthened', 
    'LAPIS_CRYSTAL': 'Magnetic', 
    'RED_SCARF': 'Loving', 
    'OPTICAL_LENS': 'Precise',
    'AOTE_STONE': 'Warped',
    'JADERALD': 'Jaded',
    'DRAGON_CLAW': 'Fabled', 
    'BLAZE_WAX': 'Waxed', 
    'NECROMANCER_BROOCH': 'Necrotic', 
    'SALMON_OPAL': 'Headstrong', 
    'PREMIUM_FLESH': 'Undead', 
    'SUSPICIOUS_VIAL': 'Suspicious', 
    'METEOR_SHARD': 'Fortified', 
    'MIDAS_JEWEL': 'Gilded', 
    'DIAMOND_ATOM': 'Perfect', 
    'ONYX': 'Fruitful', 
    'ENDSTONE_GEODE': 'Hyper', 
    'MOLTEN_CUBE': 'Cubic', 
    'DIAMONITE': 'Fleet', 
    'DRAGON_SCALE': 'Spiked', 
    'PURE_MITHRIL': 'Mithraic', 
    'SALT_CUBE': 'Salty', 
    'RUSTY_ANCHOR': 'Treacherous', 
    'AMBER_MATERIAL': 'Ambered', 
    'PRECURSOR_GEAR': 'Ancient', 
    'WITHER_BLOOD': 'Withered', 
    'DEEP_SEA_ORB': 'Submerged', 
    'BULKY_STONE': 'Bulky', 
    'KUUDRA_MANDIBLE': 'Chomp', 
    'SADAN_BROOCH': 'Empowered', 
    'BLESSED_FRUIT': 'Blessed', 
    'PETRIFIED_STARFALL': 'Stellar', 
    'GIANT_TOOTH': 'Giant', 
    'DRAGON_HORN': 'Renowned', 
    'REFINED_AMBER': 'Refined', 
    'LUCKY_DICE': 'Lucky', 
    'GOLDEN_BALL': 'Bountiful', 
    'HOT_STUFF': 'Heated', 
    'LUXURIOUS_SPOOL': 'Silky', 
    'ROCK_CANDY': 'Sweet', 
    'END_STONE_SHULKER': 'Adept', 
    'OBSIDIAN_TABLET': 'Mythical', 
    'DARK_ORB': 'Shaded', 
    'FURBALL': 'Itchy', 
    'ENDER_MONOCLE': 'Sighted', 
    'ACACIA_BIRDHOUSE': 'Forceful', 
    'BEATING_HEART': 'Bloody', 
    'MANDRAA': 'Strong', 
    'MAGMA_URCHIN': 'Hurtful', 
    'HORNS_OF_TORMENT': 'Demonic', 
    'PRECIOUS_PEARL': 'Pleasant', 
    'ECCENTRIC_PAINTING': 'Bizarre', 
    'HAZMAT_ENDERMAN': 'Slender', 
    'VITAMIN_DEATH': 'Healthy', 
    'SCORCHED_BOOKS': 'Scorching'
}

NORMAL_ENCHANTS = {
    'true_protection': [1],
    'bane_of_arthropods': [7],
    'critical': [6, 7],
    'cubism': [6],
    'ender_slayer': [6, 7],
    'execute': [6],
    'experience': [4],
    'first_strike': [5],
    'giant_killer': [6, 7],
    'lethality': [6],
    'life_steal': [5],
    'looting': [5],
    'luck': [7],
    'PROSECUTE': [6],
    'scavenger': [5],
    'sharpness': [6, 7],
    'smite': [7],
    'syphon': [4, 5],
    'titan_killer': [6, 7],
    'vampirism': [6],
    'venomous': [6],
    'triple_strike': [5],
    'vicious': [3, 4, 5],
    'chance': [4, 5],
    'power': [6, 7],
    'snipe': [4],
    'big_brain': [3, 4, 5],
    'counter_strike': [5],
    'growth': [7],
    'protection': [7],
    'caster': [6]
}

SPECIAL_ENCHANTS = {
    'overload',
    'rejuvenate',
    'sugar_rush',
    'chimera',
    'ultimate_last_stand',
    'ultimate_legion',
    'ultimate_one_for_all',
    'ultimate_soul_eater',
    'ultimate_wise',
    'ultimate_wisdom',
    'dragon_hunter'
}

CATEGORIES = {
    'weapon',
    'misc',
    'accessories',
    'consumables',
    'armor',
    'blocks'
}